### PR TITLE
Added due date option

### PR DESCRIPTION
**Pull request by Anuragpal010104**
- I added the due date option using flatpickr js library
- Included the flatpickr library in head section
- Styled the button so that it looks similar to the submit button
- Kindly review the changes and merge the PR , I am also attaching the ss for reference.
- Thank you for consideration :).
Screenshot 2023-10-02 201526
Screenshot 2023-10-02 201542

### CODE REVIEW

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
@Anuragpal010104  Resolve the conflicts

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to give a star to the repo.

**Comment by Anuragpal010104** [comment]
> @Anuragpal010104 Resolve the conflicts

Done, Sorry for the inconvenience caused, I resolved the issues but idk how it did not happened. I will make sure next time :)

**Comment by Kritika30032002** [comment]
Its okay, It sometimes happens becoz of other merged pr's

**Pull request merged**
