### PR TITLE
due date issue is solved

### PR DESCRIPTION
**Pull request by NandishM0618**
in this if user didn't specify any due date to a task the error message prompts as "Please specify a due date!!!" .

### CODE REVIEW

**Comment by nepalivai** [comment]
I am working on the issue now i will get to you shortly.

**Comment by nepalivai** [comment]
I would approve the pr request but "!!!!" are bugging me......... it could just be me but great work.

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Comment by NandishM0618** [comment]
Code peak'23

**Pull request merged**
