### PR TITLE
UI improvement, color scheme, dark mode improvement, footer & many more additional enhancement

### PR DESCRIPTION
**Pull request by Harsh2504**
All **UI changes** mentioned in the issue were made:
- Minimalist look 
- Fixing layout
- Better color theme's
- Added footer
- Improved element styling (buttons, input field)
- Mic icon added

**Additional changes :**
1. Make **Search bar** appear only when cards are added and hide when no cards are present.
2. Improved **Dark mode** a lot:
    - Customised everything to match the theme
    - Even Added Dark Mode colors to show Task priority
3. When **Check Box is checked** Task card **color changes to indicate task completed** . There is separate color introduced for this in **Dark mode too.**
4. When **CheckBox is checked** indicating task completed **Edit button hides.**
5. These two changes can be t**oggled by unchecking checkbox** too.
6. When **Edit Button is clicked title changes** from "Add your Task below:" to "Edit your Task below:" and toggles when Task is successfully edited.
7. Improved **styling of alerts** .(Task not entered!!! ,etc)
8. Improved **styling of Modals** for dark mode.
9. Added **Smooth animations** to the web page
10. Added **title** of web application to **Preloader**

### CODE REVIEW

**Comment by Harsh2504** [comment]
Resolved all the issues .
Added those all new features in my code and tweaked my code accordingly .

Even solved one more issue extra now by hiding the scroll bar of text area (description field ) you can scroll bt scroll bar is hidden to maintain a clean look .

Worked a lot for this project hoping for good points.

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Comment by Harsh2504** [comment]
> Thanks for your Valuable contribution. Don't forget to star the repo.

Do tell me if you wish to let me work on your other projects too.

**Comment by Kritika30032002** [comment]
You can work on any project according to your skills

**Pull request merged**
