### PR TITLE
updated footer and favicon

### PR DESCRIPTION
**Pull request by sanathan-git**

### CODE REVIEW

**Comment by sanathan-git** [comment]
Added Favicon
updated Footer and enhanced better UI

**Comment by Kritika30032002** [comment]
show through screenshot

**Comment by sanathan-git** [comment]
Screenshot 2023-10-12 230129
Screenshot 2023-10-12 230603

**Comment by sanathan-git** [comment]
Favicon updated  
 ----↓ 
Screenshot 2023-10-12 230804

**Comment by Kritika30032002** [comment]
previous ui was much better
I am closing this pr 
you can create a separate pr for the favicon only

**Pull request closed without merging**
