### PR TITLE
Fixed Footer Css 

### PR DESCRIPTION
**Pull request by MADHURYAHAIT**
I have fixed the footer which was previously coming up if you view it on long screen or even scale down the screen resolution.  The footer is now fixed at the bottom of the screen , no matter which ever display it is viewed on.

### CODE REVIEW

**Comment by MADHURYAHAIT** [comment]
Changed voice & scroll button css and handled what happens when you hover. It looks more even and professional now. Thankyou for letting me make changes.

**Comment by MADHURYAHAIT** [comment]
Added the Github Button as per the issue #312 both for dark / Light mode

**Comment by MADHURYAHAIT** [comment]
@Kritika30032002 when will my PR get merged ?

**Comment by MADHURYAHAIT** [comment]
@Kritika30032002 can you please review and merge it

**Comment by Kritika30032002** [comment]
it was not assigned to you

**Pull request closed without merging**
