### PR TITLE
feat: 2 column layout added

### LINKED ISSUE #343: Two-Column Layout for ToDo App
### More Effective User Experience.

The current vertical layout of the tasks in the to-do app can be enhanced by introducing a two-column layout. This change aims to provide a more visually appealing and user-friendly experience, with the task addition on the left side and task display on the right side.

## Changes Made
- **Two-Column Layout:**
  - Left Column: Task Input
  - Right Column: Task Display

## Design Idea
Screenshot from 2024-01-14 12-15-22

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
Closes #343 

## Description

Added 2 column feature (also maintained responsiveness)

## Screenshots

Screenshot 2024-01-24 at 8 29 19 PM

### CODE REVIEW

**Comment by SoumyadevSaha** [comment]
@Kritika30032002 , Is this alright ? or shall I add some more changes ?

**Comment by Kritika30032002** [comment]
you have only aligned it into 2 column 
no ui has been changed

**Comment by SoumyadevSaha** [comment]
> you have only aligned it into 2 column no ui has been changed

Oh .. I thought only 2 column layout was needed, as so is mentioned in issue #343 , I see that I need to improve the UI as well, I am on it, in the mean-time do you have any suggestions for any improvemnets to be done in the UI ?

**Comment by Kritika30032002** [comment]
It is marked as hard for this reason only. Otherwise it would have been easy issue

**Comment by SoumyadevSaha** [comment]
okay, working on it

**Pull request closed without merging**
