### PR TITLE
footer UI updated

### PR DESCRIPTION
**Pull request by Albert-2**
Hey i have done not so many but some changes in the footer
Hope you like it
Thank You...!!:)

image

### CODE REVIEW

**Comment by Kritika30032002** [comment]
program name?

**Comment by Kritika30032002** [comment]
Thanks for your Valuable contribution.
Don't forget to star the repo.

**Comment by Albert-2** [comment]
I am contributing under CODEPEAK'23
Thank you....!!

**Comment by Sami3160** [comment]
heyy @Albert-2 please recheck the css... a new UI bug is introduced after this PR is merged, 
Screenshot (133)
check this, their is horizontal scrollbar appearing, and list items are going outside of the form...

**Comment by Albert-2** [comment]
image

hey @Sami3160 
brother i don't see any scrollbar in mine
may be someone else's PR must have done that

**Comment by Albert-2** [comment]
image

hey @Sami3160 
brother whatever changes i have done are in footer only and footer is working fine
if you want then i can create a fresh new issue and solve this one

**Comment by Sami3160** [comment]
> image
> 
> hey @Sami3160 
> brother whatever changes i have done are in footer only and footer is working fine
> if you want then i can create a fresh new issue and solve this one 

Oooi i seee... Well I thought the extra space from right side came after footer changes... Well whatever I'm not frontend expert so I don't understand... But it's feels so eye poking 😂

**Comment by Sami3160** [comment]
> image
> 
> hey @Sami3160 
> brother whatever changes i have done are in footer only and footer is working fine
> if you want then i can create a fresh new issue and solve this one 

Oooi i seee... Well I thought the extra space from right side came after footer changes... Well whatever I'm not frontend expert so I don't understand... But it's feels so eye poking 😂

**Comment by Albert-2** [comment]
Actually i have done my most of contribution in UI only 
so it's quite easy and fun for me cause you actually can see how the website take shape
Btw Thank You for merging......!!
Appreciated...!

**Comment by Albert-2** [comment]
so if you need any help related UI 
i'm in....

**Comment by Sami3160** [comment]
> so if you need any help related UI 
> i'm in....
Where do you practice coding ui? I mean is their any good special website to learn or you prefer YouTube?

**Comment by Kritika30032002** [comment]
@Albert-2  Can u resolve this ui issue?

**Comment by Albert-2** [comment]
@Kritika30032002
I can solve whatever part has broken with the footer issue and make a new PR is it ok....??

**Comment by Kritika30032002** [comment]
its done now

**Pull request merged**
