### PR TITLE
Added type for task into 4 cat.

### PR DESCRIPTION
**Pull request by Anuragpal010104**
todo_type1
todo_type2
- Added four categories for tasks ->Personal, Shopping, Wishlist, Work
- Made a simple dropdown list for that.
- Attaching the SS for reference. Kindly review it 
- Give feedback if necessary :)

### CODE REVIEW

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
resolve conflicts

**Comment by Anuragpal010104** [comment]
> resolve conflicts

Done

**Comment by Anuragpal010104** [comment]
@Kritika30032002 Kindly accept the pr now :)

**Comment by Kritika30032002** [comment]
Resolve conflicts.

**Comment by Kritika30032002** [comment]
push to demo branch

**Comment by Anuragpal010104** [comment]
> create pr to demo branch

I have created a new pr please check #62 :)

**Comment by Kritika30032002** [comment]
> > create pr to demo branch
> 
> I have created a new pr please check #62 :)

its in main branch

it should be to demo branch

**Pull request closed without merging**
