### PR TITLE
Changed the task completed toggle button to checkbox

### PR DESCRIPTION
**Pull request by Virtual4087**
issue: #65

### CODE REVIEW

**Comment by Kritika30032002** [comment]
share the screenshot

**Comment by Virtual4087** [comment]
image

**Comment by Virtual4087** [comment]
is that ok?

**Comment by Kritika30032002** [comment]
yes

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to give a star to this repo.

**Pull request merged**
