### PR TITLE
Changed to Complete Mern_stack Todo_List

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Here I changed the project to Mern stack , with beautiful UI .

Frontend : react ,
Backend : Nodejs , Mongodb , express;

complete Login , Sign Up , Using JWT AUTHENTICATION !!!  , Token and  beautiful react-toastify library ;

Every User will get his own tasks after he logged In , if his tasks was already exists if not he can create , read , update , delete .

Merge it _Hacktoberfest_23 : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
yes I had added category Also so that user can select his own .

Here you go 


image

image

image


image

image



We will display all kind of errors to user in a beautiful manner using React_toastify and all complete validations are done . 

Merge it _hacktoberfest_23 : )

**Comment by Bharath-KumarReddy** [comment]
I had done with all functionalities , i had updated the project to MERN STACK  .

once go through this and merge it _hacktoberfest_23 : )

**Comment by Kritika30032002** [comment]
Create a pr to demo branch

**Comment by Bharath-KumarReddy** [comment]
okay : )

**Pull request closed without merging**
