### PR TITLE
fixed dark theme toggle button not working when click

### LINKED ISSUE #72: [BUG] : Dark theme toggle button does not work as it should
Dark theme toggle button (on the top right) this button should toggle dark theme when clicked the first time, but it is doing after clicking it the second time.

Also clicking it the first time changes the button's theme to dark mode but the whole page is still in light mode, vice versa.

Screenshot:
image

### PR DESCRIPTION
**Pull request by love-sonkar**
fixed #72 

when click in dark theme toggle button should dark theme when clicked the first time, but it is doing after clicking it the second time now it's fixed 

# video 

https://github.com/Kritika30032002/To-Do-List-Application/assets/82786865/c67945eb-9a79-496e-bab4-a0955052456c

### CODE REVIEW

**Comment by Kritika30032002** [comment]
resolve conflicts

**Comment by love-sonkar** [comment]
okay can you label this as hacktoberfest issue

**Comment by Kritika30032002** [comment]
after merge I will label it as hacktoberfest , don't worry

**Comment by love-sonkar** [comment]
hey can you check i have resolved the merge conflict

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
