### PR TITLE
saved the todo to local storage

### PR DESCRIPTION
**Pull request by Debshibraj123**
@Kritika30032002  please merge my pr and marked this as hacktoberfest

### CODE REVIEW

**Comment by Kritika30032002** [comment]
@Debshibraj123  Resolve the conflicts

**Comment by Debshibraj123** [comment]
@Kritika30032002  please check I have resolved the conflict

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Comment by Debshibraj123** [comment]
@Kritika30032002 obviously I'll

**Pull request merged**
