### PR TITLE
#2 New UI , Added TailwindCss and Time and date feature

### PR DESCRIPTION
**Pull request by taqui-786**
#2 I had made New UI with TailwindCss and added Time and date feature with proper Edit and Delete Todo.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
any ss?

**Comment by taqui-786** [comment]
> any ss?

Sorry but i can't understand what you are trying to tell?

**Comment by taqui-786** [comment]
> any ss?

Web capture_2-10-2023_14651_127 0 0 1

**Comment by Kritika30032002** [comment]
UI is not looking good
As well as don't change it into tailwindcss
let it be in bootstrap.

**Pull request closed without merging**
