### PR TITLE
change of color of the item title

### PR DESCRIPTION
**Pull request by FabianCristancho**
image

It's more readable. (issue #189)

### CODE REVIEW

**Comment by Kritika30032002** [comment]
change the color 
in light mode: black
in dark mode white

**Comment by FabianCristancho** [comment]
@Kritika30032002 ok, I'll work on this!

**Comment by FabianCristancho** [comment]
In light mode:
image

In dark mode:
image

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
