### PR TITLE
aligned the top bar :)

### PR DESCRIPTION
**Pull request by pamood**

### CODE REVIEW

**Comment by Kritika30032002** [comment]
what change you have done?

**Comment by pamood** [comment]
i aligned the top icons those were all together back and not loooked nice

**Comment by Kritika30032002** [comment]
screenshot of previous and after change?

**Comment by pamood** [comment]
if u like it you can merge my pull-request 😎

**Comment by pamood** [comment]
before
before


after
after

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to give a star to the repo.

**Comment by pamood** [comment]
Thanks, I will.

**Pull request merged**
