### PR TITLE
Error message for task added, closes #157 

### LINKED ISSUE #157: Error message in case of no text for task field
Hi, 

I would like to work on the error message in case user forget to add the task in the task field. Right now I don't see any error message for that. Please put it under Hackoberfest.

### PR DESCRIPTION
**Pull request by Shybymh**
Closes Issue #157

Added code in index.js for displaying an error message in case user didn't input any task.
The if elseif else block is changed to add this feature.

 if ( !newTaskTitle) {
    displayErrorMessage("Task not entered");
    taskeading.classList.add("hidden");
    return false;
  } else if (dueDateObj < currentDate) {
    displayErrorMessage("Due date has already passed");
    return false;
  } else {
    tasksHeading.classList.remove("hidden");
  }

### CODE REVIEW

**Comment by Kritika30032002** [comment]
resolve conflicts

**Comment by Kritika30032002** [comment]
take the updated code pull then add your changes accordingly

**Comment by Shybymh** [comment]
@Kritika30032002 PR updated ,please review.

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
