### PR TITLE
enhanced UI

### PR DESCRIPTION
**Pull request by guntarakesh**
image

### CODE REVIEW

**Comment by guntarakesh** [comment]
Ref #17 , @Kritika30032002 please Review my PR .

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Comment by guntarakesh** [comment]
@Kritika30032002 can you please resolve my query , in my Hacktoberfest Profile its showing my PR is not Accepted .

**Comment by Kritika30032002** [comment]
Now check after 10-15 min later.

**Comment by guntarakesh** [comment]
ok , ThankYou .

**Pull request merged**
