### PR TITLE
Add Priority Labels

### PR DESCRIPTION
**Pull request by gauravbhaskar080**
1. Add Priority to the tasks , Like : Low , Medium or High
2. Update inde.html , style.css and index.js files.

### CODE REVIEW

**Comment by Kritika30032002** [comment]
show functioning through video

**Comment by Kritika30032002** [comment]
add priority using dropdown rather than radio

**Comment by gauravbhaskar080** [comment]
https://github.com/Kritika30032002/To-Do-List-Application/assets/97628596/afcdf775-488e-4e3a-9e04-d4ac8ab8342a

**Comment by Kritika30032002** [comment]
resolve conflicts by taking pull and update accordingly

**Comment by sagar803** [comment]
we can also indicate priority of a task based on its background color , 
for example
green - high priority 
yellow - medium priority 
red - low priority

**Pull request closed without merging**
