### PR TITLE
FEAT: Modified UI

### LINKED ISSUE #148: FEAT: Responsive and Modified UI
UI is breaking in mobile screen and the desktop screen ui is not so attractive and we can divide the list into two parts like "Done To Dos" and "Not Done To Dos".
@Kritika30032002 can I work on this?

### PR DESCRIPTION
**Pull request by asheshmandal2003**
fixes #148
 

Light Mode:

Screenshot 2023-10-16 121502

Dark Mode:

Screenshot 2023-10-16 121555

### CODE REVIEW

**Comment by Kritika30032002** [comment]
resolve conflicts

**Comment by asheshmandal2003** [comment]
@Kritika30032002 please check now.

**Comment by Kritika30032002** [comment]
resolve conflicts

**Comment by asheshmandal2003** [comment]
Already did that previously! Now I'm doing this for the 2nd time. Please kindly check it now @Kritika30032002 .

**Comment by Kritika30032002** [comment]
Thanks for your valuable contribution.
Don't forget to star the repo.

**Pull request merged**
