### PR TITLE
fixed overflow issue in add item box

### LINKED ISSUE #59: [bug] : add item box is overflowing
the add item box is overflowing 

# screenshot 

ooo

### PR DESCRIPTION
**Pull request by love-sonkar**
fixed #59 add item is overflowing from box i have fixed this issue 

# screenshot 
fixedooo

Please approve this issue under hacktoberfest

### CODE REVIEW

**Comment by Kritika30032002** [comment]
Resolve conflicts

**Comment by love-sonkar** [comment]
okay let me check

**Comment by Kritika30032002** [comment]
@love-sonkar  this issue in not there now

**Comment by love-sonkar** [comment]
okay thanks

**Comment by Kritika30032002** [comment]
You can contribute in another issue.
Thanks

**Pull request closed without merging**
