### PR TITLE
adding selection button

### LINKED ISSUE #27: adding selection button

### PR DESCRIPTION
**Pull request by SoumodeepDas**
Fixed #27

### CODE REVIEW

**Comment by SoumodeepDas** [comment]
before:
Screenshot 2023-10-02 190139
after:
image

**Comment by Kritika30032002** [comment]
UI needs improvement .
Also it has merging conflicts

**Comment by SoumodeepDas** [comment]
No

**Comment by Kritika30032002** [comment]
okay

**Pull request closed without merging**
